name: Generate Latest Scores

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Recreate google_credentials.json from secret
      run: echo "${{ secrets.GOOGLE_CREDS_BASE64 }}" | base64 -d > google_credentials.json

    - name: Install dependencies
      run: pip install google-api-python-client google-auth

    - name: Run the script
      run: python generate_latest_scores.py

    - name: Commit and push latest_scores.json
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add latest_scores.json
        git commit -m "🔄 Auto-update latest_scores.json from workflow" || echo "No changes to commit"
        git push
